### ISSUE TITLE
[Documentation] UpwardConnector Docs

### ISSUE THREAD

**Issue by tjwiebell** [magento-research/upward-php#48]
Edit and publish documentation for UpwardConnector module and cloud installation steps.

**Comment by jcalcaben** [comment]
A reviewable copy of this draft can be found here:
https://gist.github.com/jcalcaben/607db70c8c8d8ec9eaf9004c832b309c

**Comment by awilcoxa** [comment]
Closing pending publish action by cloud docs team, need to ensure it's completed on their end @jcalcaben
