### ISSUE TITLE
Venia search functionality not working

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/upward-php#54]
Pre-condition:
PHP Upward should be used.

Description:
Click on search icon and search for some products > user is displayed with "Data Fetch Error" instead of results.

1. Go to Venia storefront and click on search icon.
2. Enter some valid SKU ex: VT11 and search.

Expected:
Product whose SKU is VT11 should be displayed.

Actual:
Getting "Data Fetch Error" message displayed.

Screen:

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/615fb87d-aab5-4fb9-97d4-5a68e5781240)

**Comment by tjwiebell** [comment]
There was a compatibility issue with ElasticSearch that was not documented and was causing this error. Switching to the MySQL engine resolved the error, there was no issue with this package. Closing and will open a new issue in scope of Venia Sample Data to support ElasticSearch as the FTS engine.
