### ISSUE TITLE
Packaging for 1.0 Release

### ISSUE THREAD

**Issue by tjwiebell** [magento-research/upward-php#59]
There are a few packaging questions that we need to answer before UPWARD-PHP and the Magento module are ready for public consumption. Figure out what existing core infrastructure is in place for publishing packages on Packagist, and what that process is.

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/DEVOPS-4935

**Comment by cherdman** [comment]
Closing this issue. Packages published on Packagist:

https://packagist.org/packages/magento/upward
https://packagist.org/packages/magento/module-upward-connector
