### ISSUE TITLE
Release new upward-php version after #1318 pushed to master.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/upward-php#66]
`upward-php` is ready for release, but given it has a dependency on `upward-spec` and lives outside of the monorepo, there are some steps we need to take after that package has been published. This repo does not see a lot of activity, so `develop` is effectively serving as the release branch.

#### Steps for Publication

_After `@magento/upward-spec@2.2.0` is published_

1. `git fetch; git checkout -b pub/1.1.0-version-bump origin/develop`
2. `npm install`, commit `package-lock.json` changes, verify tests pass (`npm run test:spec`)
3. Push/create PR, approve/merge (we don't have parallel development happening, so `develop` is effectively the release branch)
4.. Merge `develop` into `master`, create `1.1.0` tag, push

**Comment by tjwiebell** [comment]
@bbatsche - Wrote up these instructions for the team on the off chance that I'm not available for release next Tuesday. Since you and Zetlen did the release last time, would you mind looking over the steps and verify I didn't miss anything?

**Comment by bbatsche** [comment]
This all checks out, I should be available as a standby if you need me
