### ISSUE TITLE
Cannot install with Magneto 2.3.3

### ISSUE THREAD

**Issue by opepin** [magento-research/upward-php#74]
Conflict with symphony/yaml version 

    - Conclusion: don't install magento/module-upward-connector 1.0.1
    - Conclusion: remove symfony/translation v4.3.6
    - Conclusion: don't install symfony/translation v4.3.6
    - Can only install one of: symfony/yaml[v3.4.9, v4.3.6].
    - Installation request for symfony/yaml (locked at v4.3.6) -> satisfiable by symfony/yaml[v4.3.6].

 Maybe upgrade to : 
 "symfony/yaml": "^2.3||^3.3", => "symfony/yaml": "^2.3||^3.3||^4"

**Comment by tjwiebell** [comment]
Fixed by #75
